import Head from "next/head";
import React from "react";
import { Footer } from "../Footer";
import Hero from "../Hero";
import Navbar from "../Navbar";

export default function Layout(props) {
  const { children } = props;
  return (
    <div className="">
      <Head>
        <title>PT HAMENGKU KARYA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Navbar />

      <div className="">{children}</div>
      <Footer />
    </div>
  );
}
