import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div className="items-center max-sm">
      <Head>
        <title>PT HAMENGKU KARYA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />

      <div className="min-[600px]:mx-64">
        <h1 className=" text-2xl text-center text-zinc-600 dark:text-zinc-600 mb-5 ">
          WELCOME TO PT. HAMENGKU KARYA
        </h1>
        <p className="m-auto text-[13px] max-[1240px]:mx-8   text-center list-outside text-zinc-500 dark:text-zinc-500 ">
          PT.Hamengku Karya Founded in 1981, which initially Specializes
          in&nbsp;
          <b>Mechanical, Electrical & Plumbing Construction</b> for retail,
          restaurants, shopping centers, hotels and hospitality projects
          throughout Indonesia. In line with experience, we also expand our
          business in the fields of&nbsp;
          <b>Civil works, building automation & IT infrastructure.</b> Also in
          several fields of work to maintain and strengthen our services in
          the&nbsp;
          <b>Manage services and Internet Service Providers.</b>
        </p>
      </div>
      {/* <div className="absolute top-0 left-0 right-0 bottom-100 mt-96  bg-zinc-900/30 z-[2] " /> */}
      <div className="max-w-md mx-6 mt-20 mb-14 bg-white rounded-xl shadow-md overflow-hidden md:max-w-max ">
        <div className="md:flex ">
          <div className="p-8 ">
            <Image
              className="rounded-2xl "
              height="900"
              width="3000"
              src="https://images.unsplash.com/photo-1621905252507-b35492cc74b4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80"
              alt="Modern building architecture"
            />
          </div>
          <div className="p-8">
            <div className="uppercase tracking-wide text-sm text-indigo-500 font-semibold">
              {/* <h1 className="inline-block p-4 rounded-t-lg border-b-2">
                1.
              </h1> */}
              Civil work
            </div>
            <a
              href="#"
              className="block mt-1 text-lg leading-tight font-medium text-black hover:underline"
            >
              {/* Incredible accomodation for your team */}
            </a>
            <p className="mt-2 text-slate-500">
              Start from planning, designing, estimating, supervising
              construction, transportation of materials and site development for
              Civil work.
            </p>
          </div>
          <div className="p-8">
            <div className="uppercase tracking-wide text-sm text-indigo-500 font-semibold">
              Electrical work
            </div>
            <a
              href="#"
              className="block mt-1 text-lg leading-tight font-medium text-black hover:underline"
            >
              {/* Incredible accomodation for your team */}
            </a>
            <p className="mt-2 text-slate-500">
              Start from planning, designing, estimating, supervising
              construction, transportation of materials and site development for
              Electrical work.
            </p>
          </div>
          <div className="p-8">
            <div className="uppercase tracking-wide text-sm text-indigo-500 font-semibold">
              Plumbing wor
            </div>
            <a
              href="#"
              className="block mt-1 text-lg leading-tight font-medium text-black hover:underline"
            >
              {/* Incredible accomodation for your team */}
            </a>
            <p className="mt-2 text-slate-500">
              Start from planning, designing, estimating, supervising
              construction, transportation of materials and site development for
              Plumbing work.
            </p>
            <div className="p-8"></div>
            <br></br>
            <h1 className="text-center">
              <Link href="/service" passHref>
                <button className="text-white bg-red-700 hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">
                  View All Service
                </button>
              </Link>
            </h1>
          </div>
        </div>
      </div>
      <div className="max-w-md mx-6 mt-14 mb-20 py-9 bg-white rounded-xl shadow-md overflow-hidden md:max-w-max ">
        <div className="min-[600px]:justify-center max-[1240px]:ml-2 min-[600px]:grid grid-cols-4 gap-4">
          <div className="flex mt-9 relative w-[290px] transition ease-in-out delay-10 hover:-translate-y-1 hover:scale-110 duration-300 mx-5 ">
            <Image
              className="rounded-lg h-60 w-full object-cover md:h-full md:w-72"
              src="https://images.unsplash.com/photo-1530240852689-f7a9c6d9f6c7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=385&q=80"
              height="310"
              width="310"
            />
            <Link href="/service" passHref>
              <div className="absolute bottom-0 left-0 right-0 px-4 py-2 bg-red-600 text-center opacity-70  rounded-lg">
                <h3 className="text-xl text-white font-bold hover:text-red-200 ">
                  Various Services
                </h3>
                <h1 className="mt-2 text-sm text-white">Specializes</h1>
              </div>
            </Link>
          </div>
          <div className="flex mt-9 relative w-[290px] transition ease-in-out  delay-10 hover:-translate-y-1 hover:scale-110 duration-300 mx-5 ">
            <Image
              className="rounded-lg h-60 w-full object-cover md:h-full md:w-72 "
              src="https://images.unsplash.com/photo-1636414405519-ba85fdb9a155?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"
              height="310"
              width="310"
            />
            <Link href="/project" passHref>
              <div className="absolute bottom-0 left-0 right-0 px-4 py-2 bg-red-600 text-center opacity-70  rounded-lg">
                <h3 className="text-xl text-white font-bold hover:text-red-200 ">
                  Project
                </h3>
                <h1 className="mt-2 text-sm text-white">Specializes</h1>
              </div>
            </Link>
          </div>
          <div className="flex mt-9 relative w-[290px] transition ease-in-out delay-10 hover:-translate-y-1 hover:scale-110 duration-300 mx-5 ">
            <Image
              className="rounded-lg h-60 w-full object-cover md:h-full md:w-72"
              src="https://images.unsplash.com/photo-1629479787958-ead6859fcdf2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjUyfHxwbHVtYmluZyUyMENvbnN0cnVjdGlvbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=400&q=60"
              height="310"
              width="310"
            />
            <Link href="/contact" passHref>
              <div className="absolute bottom-0 left-0 right-0 px-4 py-2 bg-red-600 text-center opacity-70 rounded-lg">
                <h3 className="text-xl text-white font-bold hover:text-red-200 ">
                  Reasonable Cost
                </h3>
                <h1 className="mt-2 text-sm text-white">
                  Efficiently & economically
                </h1>
              </div>
            </Link>
          </div>
          <div className="flex mt-9 relative w-[290px] transition ease-in-out delay-10 hover:-translate-y-1 hover:scale-110 duration-300 mx-5 ">
            <Image
              className="rounded-lg h-60 w-full object-cover md:h-full md:w-72"
              src="https://images.unsplash.com/photo-1563884705074-7c8b15f16295?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=465&q=80"
              height="310"
              width="310"
            />
            <Link href="/client" passHref>
              <div className="absolute bottom-0 left-0 right-0 px-4 py-2 bg-red-600 text-center opacity-70  rounded-lg">
                <h3 className="text-xl text-white font-bold hover:text-red-200 ">
                  On Target
                </h3>
                <h1 className="mt-2 text-sm text-white">Goals</h1>
              </div>
            </Link>
          </div>
        </div>
      </div>
      <div className="max-w-md mx-3 mt-14 mb-20 py-9 bg-white rounded-xl shadow-md overflow-hidden md:max-w-max ">
        <div className="md:flex ">
          <div className="text-left ml-9 text-zinc-500 p-2  max-[1240px]:ml-5  ">
            <h1 className="text-[28px] mt-5 font-semibold">CONTACT US</h1>
            <h1 className="text-[20px] mt-5 font-semibold ">
              GENERAL INFORMATION,
              <br />
              PT HAMENGKU KARYA (BALI)
            </h1>
            <Link href="/contact" passHref>
              <h1 className="mt-5 mb-5 text-4xl text-red-500 font-semibold hover:text-red-700">
                (0361) 471 4819
              </h1>
              <p className="text-red-500 hover:text-red-700 font-semibold mb-5">
                admin@hamengkukarya.co.id
              </p>
            </Link>
            <p>
              We are at your service 24/7, looking for a<br /> solution to any
              Construction problem
              <br /> you may have!
            </p>
          </div>
          <div>
            <iframe
              className="rounded-lg ml-9 mr-5  max-[1240px]:ml-0 max-[1240px]:w-96 max-[1240px]:mx-9"
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3944.634203547982!2d115.18246501488491!3d-8.631070873166738!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd23950b84a2619%3A0x348da9111968348d!2sPT.%20Hamengku%20Karya!5e0!3m2!1sen!2sid!4v1669194201180!5m2!1sen!2sid"
              width="850"
              height="360"
              allowfullscreen=""
              loading="lazy"
              referrerpolicy="no-referrer-when-downgrade"
            ></iframe>
          </div>
        </div>
      </div>
    </div>
  );
}
